// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum LiveMediaApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum LiveMediaEventType: Int, CaseIterable {
  case initialized = 0
  case playing = 1
  case buffering = 2
  case completed = 3
  case reconnecting = 4
  case stopped = 5
  case error = 6
}

/// Generated class from Pigeon that represents data sent in messages.
struct LiveEngineConfiguration: Hashable, CustomStringConvertible {
  var enableHardwareAcceleration: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LiveEngineConfiguration? {
    let enableHardwareAcceleration: Bool? = nilOrValue(pigeonVar_list[0])

    return LiveEngineConfiguration(
      enableHardwareAcceleration: enableHardwareAcceleration
    )
  }
  func toList() -> [Any?] {
    return [
      enableHardwareAcceleration
    ]
  }
  static func == (lhs: LiveEngineConfiguration, rhs: LiveEngineConfiguration) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LiveMediaApiPigeonInternal.deepEquals(lhs.enableHardwareAcceleration, rhs.enableHardwareAcceleration)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LiveEngineConfiguration")
    LiveMediaApiPigeonInternal.deepHash(value: enableHardwareAcceleration, hasher: &hasher)
  }

  public var description: String {
    return "LiveEngineConfiguration(enableHardwareAcceleration: \(String(describing: enableHardwareAcceleration)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LiveMediaEvent: Hashable, CustomStringConvertible {
  var type: LiveMediaEventType
  var message: String? = nil
  var retryCount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LiveMediaEvent? {
    let type = pigeonVar_list[0] as! LiveMediaEventType
    let message: String? = nilOrValue(pigeonVar_list[1])
    let retryCount: Int64? = nilOrValue(pigeonVar_list[2])

    return LiveMediaEvent(
      type: type,
      message: message,
      retryCount: retryCount
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      message,
      retryCount,
    ]
  }
  static func == (lhs: LiveMediaEvent, rhs: LiveMediaEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LiveMediaApiPigeonInternal.deepEquals(lhs.type, rhs.type) && LiveMediaApiPigeonInternal.deepEquals(lhs.message, rhs.message) && LiveMediaApiPigeonInternal.deepEquals(lhs.retryCount, rhs.retryCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LiveMediaEvent")
    LiveMediaApiPigeonInternal.deepHash(value: type, hasher: &hasher)
    LiveMediaApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    LiveMediaApiPigeonInternal.deepHash(value: retryCount, hasher: &hasher)
  }

  public var description: String {
    return "LiveMediaEvent(type: \(String(describing: type)), message: \(String(describing: message)), retryCount: \(String(describing: retryCount)))"
  }
}

private class LiveMediaApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LiveMediaEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return LiveEngineConfiguration.fromList(self.readValue() as! [Any?])
    case 131:
      return LiveMediaEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LiveMediaApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LiveMediaEventType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? LiveEngineConfiguration {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LiveMediaEvent {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LiveMediaApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LiveMediaApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LiveMediaApiPigeonCodecWriter(data: data)
  }
}

class LiveMediaApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LiveMediaApiPigeonCodec(readerWriter: LiveMediaApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LiveMediaHostApi {
  func initialize(configuration: LiveEngineConfiguration) async throws -> Bool
  func play(url: String) async throws -> Bool
  func stop() async throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LiveMediaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { LiveMediaApiPigeonCodec.shared }
  /// Sets up an instance of `LiveMediaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LiveMediaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_live_media_plugin.LiveMediaHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configurationArg = args[0] as! LiveEngineConfiguration
        Task { @MainActor in
          do {
            let result = try await api.initialize(configuration: configurationArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_live_media_plugin.LiveMediaHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.play(url: urlArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_live_media_plugin.LiveMediaHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.stop()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LiveMediaFlutterApiProtocol {
  func onEvent(event eventArg: LiveMediaEvent) async throws
}
class LiveMediaFlutterApi: LiveMediaFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: LiveMediaApiPigeonCodec {
    return LiveMediaApiPigeonCodec.shared
  }
  func onEvent(event eventArg: LiveMediaEvent) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.flutter_live_media_plugin.LiveMediaFlutterApi.onEvent\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
